version: '3.6'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6380  --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ./data/master:/data

  slave1:
    image: redis
    container_name: redis-slave
    restart: always
    command: redis-server --slaveof master 6380 --port 6381 --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ./data/slave1:/data
